// This file is auto-generated by @hey-api/openapi-ts

export const $SaleEntity = {
    type: 'object',
    properties: {}
} as const;

export const $AuthInput = {
    type: 'object',
    properties: {
        username: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['username', 'password']
} as const;