// This file is auto-generated by @hey-api/openapi-ts

export type SaleEntity = {
    [key: string]: unknown;
};

export type AuthInput = {
    username: string;
    password: string;
};

export type GetHelloResponse = (string);

export type GetHelloError = unknown;

export type CreateSaleData = {
    body: SaleEntity;
};

export type CreateSaleResponse = (unknown);

export type CreateSaleError = unknown;

export type GetUserData = {
    path: {
        username: string;
    };
};

export type GetUserResponse = (unknown);

export type GetUserError = unknown;

export type GetSalesResponse = (unknown);

export type GetSalesError = unknown;

export type LoginData = {
    body: AuthInput;
};

export type LoginResponse = ({
    [key: string]: unknown;
});

export type LoginError = unknown;

export type CreateUserData = {
    body: AuthInput;
};

export type CreateUserResponse = (unknown);

export type CreateUserError = unknown;